CREATE DATABASE IF NOT EXISTS PokeScrandle;

USE PokeScrandle;

CREATE TABLE IF NOT EXISTS Pokemon(
	DexId INT NOT NULL AUTO_INCREMENT,
	Name NVARCHAR(50) NOT NULL,
	Votes INT DEFAULT 0,
	EloRatings INT NOT NULL DEFAULT 1200,
	
	PRIMARY KEY (DexId)
);