CREATE DATABASE IF NOT EXISTS PokeScrandle;

USE PokeScrandle;

CREATE TABLE IF NOT EXISTS Pokemon(
	DexId INT IDENTITY(1,1),
	Name NVARCHAR(50) NOT NULL,
	Url VARCHAR(2083) NOT NULL, -- Image VARBINARY,
	Votes INT DEFAULT 0,
	
	CONSTRAINT PK_Pokemon PRIMARY KEY(DexId)
);

CREATE UNIQUE INDEX UX_Pokemon_Name ON Pokemon(Name);